import type { Metadata } from "next";

import "../globals.css";
import { cn } from "@/lib/utils";
import fonts from "@/constants/fonts";
import { Navbar } from "@/components/common/navbar";

export const metadata: Metadata = {
  title: "Four Sense",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        suppressHydrationWarning
        className={cn(fonts.className, "bg-[#F9D9B1]")}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
