export * from './loader'
export * from './home'
export * from './green-section'
export * from './yellow-section'
export * from './orange-section'
export * from './team-section'
export * from './explore-secion'